services:
  openlaunch:
    build: .
    environment:
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      USE_SERVICE: ${USE_SERVICE}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      UNSUBSCRIBE_KEY: ${UNSUBSCRIBE_KEY}
    ports:
      - "8080:8080"
    volumes:
      - ./src/OpenLaunch/Database:/app/Database